Projekt3/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Projekt3.Models;
using Projekt3.Repositories;

namespace Projekt3.Views
{
    public class AuthorsController : Controller
    {
        private readonly AuthorsRepository authorsRepository;

        public AuthorsController(AuthorsRepository authorsRepository)
        {
            this.authorsRepository = authorsRepository;
        }

        [Authorize(Roles = "user, admin")]
        // GET: Authors
        public ActionResult Index()
        {
            return View(authorsRepository.FindAll());
        }

        [Authorize(Roles = "user, admin")]
        // GET: Authors/Details/5
        public ActionResult Details(int id)
        {
            return View(authorsRepository.FindById(id));
        }

        [Authorize(Roles = "admin")]
        // GET: Authors/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        // POST: Authors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Name,LastName")] Author author)
        {
            if (ModelState.IsValid)
            {
                authorsRepository.Save(author);
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        [Authorize(Roles = "admin")]
        // GET: Authors/Edit/5
        public ActionResult Edit(int id)
        {
            return View(authorsRepository.FindById(id));
        }

        [Authorize(Roles = "admin")]
        // POST: Authors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int authorId, [Bind("authorId,Name,LastName")] Author author)
        {
            if (ModelState.IsValid)
            {
                authorsRepository.Save(author);
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        [Authorize(Roles = "admin")]
        // GET: Authors/Delete/5
        public ActionResult Delete(int id)
        {
            return View(authorsRepository.FindById(id));
        }

        [Authorize(Roles = "admin")]
        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            authorsRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Projekt3/Controllers/BooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Projekt3.Data;
using Projekt3.Helpers;
using Projekt3.Models;
using Projekt3.Repositories;

namespace Projekt3.Views
{
    public class BooksController : Controller
    {
        private readonly BooksRepository booksRepository;
        private readonly AuthorsRepository authorsRepository;
        private readonly AuthorsHelper authorsHelper;

        public BooksController(
            BooksRepository booksRepository,
            AuthorsRepository authorsRepository,
            AuthorsHelper authorsHelper)
        {
            this.booksRepository = booksRepository;
            this.authorsHelper = authorsHelper;
            this.authorsRepository = authorsRepository;
        }

        [Authorize(Roles = "user, admin")]
        // GET: Books
        public ActionResult Index()
        {
            return View(booksRepository.FindAll());
        }

        [Authorize(Roles = "user, admin")]
        // GET: Books/Details/5
        public ActionResult Details(int id)
        {
            return View(booksRepository.FindById(id));
        }

        [Authorize(Roles = "admin")]
        // GET: Books/Create
        public ActionResult Create()
        {
            ViewBag.AuthorId = authorsHelper.ToSelectList(authorsRepository.FindAll());
            return View();
        }

        [Authorize(Roles = "admin")]
        // POST: Books/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Title,Publisher,PublicationDate,AuthorId")] Book book)
        {
            if (ModelState.IsValid)
            {
                booksRepository.Save(book);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.AuthorId = authorsHelper.ToSelectList(authorsRepository.FindAll());
            return View(book);
        }

        [Authorize(Roles = "admin")]
        // GET: Books/Edit/5
        public ActionResult Edit(int id)
        {
            var book = booksRepository.FindById(id);
            ViewBag.AuthorId = authorsHelper.ToSelectList(authorsRepository.FindAll(), book.Author.authorId);
            return View(book);
        }

        [Authorize(Roles = "admin")]
        // POST: Books/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int bookId, [Bind("bookId,Title,Publisher,PublicationDate,AuthorId")] Book book)
        {
            if (ModelState.IsValid)
            {
                booksRepository.Save(book);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.AuthorId = authorsHelper.ToSelectList(authorsRepository.FindAll());
            return View(book);
        }

        [Authorize(Roles = "admin")]
        // GET: Books/Delete/5
        public ActionResult Delete(int id)
        {
            return View(booksRepository.FindById(id));
        }

        [Authorize(Roles = "admin")]
        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            booksRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Projekt3/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-lumen.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap-lumen.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap-lumen.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Library</a>
            </div>

            <div class=" collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                @if (SignInManager.IsSignedIn(User))
                {
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Books" asp-action="Index">Books</a></li>
                        <li><a asp-area="" asp-controller="Authors" asp-action="Index">Authors</a></li>
                    </ul>
                }
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Library</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>